[package]
name = "client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
gfx.workspace = true
data.workspace = true
gameplay.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
