[package]
name = "gfx"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
tracing.workspace = true
bytemuck.workspace = true
glam.workspace = true
hecs.workspace = true
pollster.workspace = true
wgpu.workspace = true
winit.workspace = true
lazy_static.workspace = true
image.workspace = true
gameplay.workspace = true
data.workspace = true
world.workspace = true
